main: net.catharos.societies.bukkit.SocietiesPlugin
name: Societies
version: 0.1
softdepend: [ Vault, SimpleClans, SimpleClans2 ]
authors:
  - p000ison
commands:
  society:
    aliases: [ societies, s ]
    description: Society main command
    permission: societies.member
permissions:
  societies.member:
    default: true
    children:
      societies.create: true
      societies.tag: true
      societies.profile: true
      societies.lookup: true
      societies.coords: true
      societies.vitals: true
      societies.roster: true
      societies.list: true
      societies.trust: true
      societies.distrust: true
      societies.promote: true
      societies.demote: true
      societies.join: true
      societies.invite: true
      societies.kick: true
      societies.alliances: true
      societies.rivalries: true
      societies.leave: true
      societies.vote.accept: true
      societies.vote.deny: true
      societies.vote.abstain: true
      societies.vote.cancel: true
      societies.home.set: true
      societies.home.regroup: true
      societies.home.remove: true
      societies.home.teleport: true
      societies.rank.create: true
      societies.rank.remove: true
      societies.rank.list: true
      societies.rank.assign: true
      societies.rank.deassign: true
      societies.rank.rules.assign: true
      societies.rank.rules.remove: true
      societies.rank.rules.list: true
      societies.allies.add: true
      societies.allies.remove: true
      societies.allies.list: true
      societies.rivals.add: true
      societies.rivals.remove: true
      societies.rivals.list: true
      societies.ff: true
      societies.group-ff: true
  societies.moderator:
    default: false
    children:
      societies.member: true
      societies.verify: true
      societies.disprove: true
  societies.admin:
    default: op
    children:
      societies.moderator: true
      societies.reload: true
      societies.backup: true
  societies.create:
    description: Allows you to use the command "/society create [name] [tag]"
  societies.tag:
    description: Allows you to use the command "/society tag [newTag]"
  societies.profile:
    description: Allows you to use the command "/society profile [--society]"
  societies.lookup:
    description: Allows you to use the command "/society lookup [--member]"
  societies.coords:
    description: Allows you to use the command "/society coords [--page]"
  societies.vitals:
    description: Allows you to use the command "/society vitals [--page]"
  societies.roster:
    description: Allows you to use the command "/society roster [--page]"
  societies.list:
    description: Allows you to use the command "/society list [--page]"
  societies.trust:
    description: Allows you to use the command "/society trust [--member]"
  societies.distrust:
    description: Allows you to use the command "/society distrust [--member]"
  societies.promote:
    description: Allows you to use the command "/society promote [--member]"
  societies.demote:
    description: Allows you to use the command "/society demote [--member]"
  societies.join:
    description: Allows you to use the command "/society join [society]"
  societies.invite:
    description: Allows you to use the command "/society invite [member]"
  societies.kick:
    description: Allows you to use the command "/society kick [member]"
  societies.alliances:
    description: Allows you to use the command "/society alliances"
  societies.rivalries:
    description: Allows you to use the command "/society rivalries"
  societies.leave:
    description: Allows you to use the command "/society leave"
  societies.vote.accept:
    description: Allows you to use the command "/society accept"
  societies.vote.deny:
    description: Allows you to use the command "/society deny"
  societies.vote.abstain:
    description: Allows you to use the command "/society abstain"
  societies.vote.cancel:
    description: Allows you to use the command "/society cancel"
  societies.home.set:
    description: Allows you to use the command "/society home set [--location]"
  societies.home.regroup:
    description: Allows you to use the command "/society home regroup"
  societies.home.remove:
    description: Allows you to use the command "/society home remove"
  societies.home.teleport:
    description: Allows you to use the command "/society home"
  societies.rank.create:
    description: Allows you to use the command "/society rank create [name] [--priority]"
  societies.rank.remove:
    description: Allows you to use the command "/society rank remove [name]"
  societies.rank.list:
    description: Allows you to use the command "/society rank list [--page]"
  societies.rank.assign:
    description: Allows you to use the command "/society rank assign [member] [rank]"
  societies.rank.deassign:
    description: Allows you to use the command "/society rank deassign [rank]"
  societies.rank.rules.assign:
    description: Allows you to use the command "/society rank rules assign [rank] [rule]"
  societies.rank.rules.remove:
    description: Allows you to use the command "/society rank rules remove [rank] [rule]"
  societies.rank.rules.list:
    description: Allows you to use the command "/society rank rules list [rank]"
  societies.allies.add:
    description: Allows you to use the command "/society allies add [society]"
  societies.allies.remove:
    description: Allows you to use the command "/society allies remove [society]"
  societies.allies.list:
    description: Allows you to use the command "/society allies"
  societies.rivals.add:
    description: Allows you to use the command "/society rivals create [society]"
  societies.rivals.remove:
    description: Allows you to use the command "/society rivals remove [society]"
  societies.rivals.list:
    description: Allows you to use the command "/society rivals"
  societies.ff:
    description: Allows you to use the command "/society ff"
  societies.group-ff:
    description: Allows you to use the command "/society groupff"
  societies.verify:
    description: Allows you to use the command "/society verify [society]"
  societies.disprove:
    description: Allows you to use the command "/society disprove [society]"
  societies.reload:
    description: Allows you to use the command "/society reload"
  societies.backup:
    description: Allows you to use the command "/society backup [file]"

