main: net.catharos.societies.bukkit.SocietiesPlugin
name: Societies
version: 0.1
softdepend: [ Vault ]
authors:
    - p000ison
commands:
  society:
    aliases: [ societies, s ]
    description: Society main command
    usage: None
